# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.column_executor_type import ColumnExecutorType

class TestColumnExecutorType(unittest.TestCase):
    """ColumnExecutorType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testColumnExecutorType(self):
        """Test ColumnExecutorType"""
        # inst = ColumnExecutorType()

if __name__ == '__main__':
    unittest.main()
