# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.custom_model_update_request import CustomModelUpdateRequest

class TestCustomModelUpdateRequest(unittest.TestCase):
    """CustomModelUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomModelUpdateRequest:
        """Test CustomModelUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomModelUpdateRequest`
        """
        model = CustomModelUpdateRequest()
        if include_optional:
            return CustomModelUpdateRequest(
                name = '0',
                api_base_url = '',
                model_id = '0',
                api_key = '',
                compatibility = 'O',
                provider = 'openai_compatible',
                reasoning_effort = 'none'
            )
        else:
            return CustomModelUpdateRequest(
        )
        """

    def testCustomModelUpdateRequest(self):
        """Test CustomModelUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
