# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.output_format import OutputFormat

class TestOutputFormat(unittest.TestCase):
    """OutputFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOutputFormat(self):
        """Test OutputFormat"""
        # inst = OutputFormat()

if __name__ == '__main__':
    unittest.main()
