# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt-python-sdk.models.api_integration_authentication_method import ApiIntegrationAuthenticationMethod

class TestApiIntegrationAuthenticationMethod(unittest.TestCase):
    """ApiIntegrationAuthenticationMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiIntegrationAuthenticationMethod:
        """Test ApiIntegrationAuthenticationMethod
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiIntegrationAuthenticationMethod`
        """
        model = ApiIntegrationAuthenticationMethod()
        if include_optional:
            return ApiIntegrationAuthenticationMethod(
                auth_type = api_key,
                description = 'API Key',
                beta = True,
                link = 'https://api.com',
                recommended_for_internal_assistant = True,
                recommended_for_public_facing_bot = True
            )
        else:
            return ApiIntegrationAuthenticationMethod(
                auth_type = api_key,
                description = 'API Key',
                link = 'https://api.com',
        )
        """

    def testApiIntegrationAuthenticationMethod(self):
        """Test ApiIntegrationAuthenticationMethod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
