# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.agent_team_project_search_request import AgentTeamProjectSearchRequest

class TestAgentTeamProjectSearchRequest(unittest.TestCase):
    """AgentTeamProjectSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentTeamProjectSearchRequest:
        """Test AgentTeamProjectSearchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentTeamProjectSearchRequest`
        """
        model = AgentTeamProjectSearchRequest()
        if include_optional:
            return AgentTeamProjectSearchRequest(
                name = '',
                limit = 56,
                pagination = flowhunt.models.pagination.Pagination(
                    sorting_key_value = '', 
                    scroll_id = 'scroll_id_12345', )
            )
        else:
            return AgentTeamProjectSearchRequest(
        )
        """

    def testAgentTeamProjectSearchRequest(self):
        """Test AgentTeamProjectSearchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
