# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.flow_batch_artefact_info import FlowBatchArtefactInfo

class TestFlowBatchArtefactInfo(unittest.TestCase):
    """FlowBatchArtefactInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlowBatchArtefactInfo:
        """Test FlowBatchArtefactInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlowBatchArtefactInfo`
        """
        model = FlowBatchArtefactInfo()
        if include_optional:
            return FlowBatchArtefactInfo(
                id = '',
                name = '',
                size = 56,
                mime_type = '',
                download_url = ''
            )
        else:
            return FlowBatchArtefactInfo(
                id = '',
                name = '',
        )
        """

    def testFlowBatchArtefactInfo(self):
        """Test FlowBatchArtefactInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
