# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.zendesk_kb_section_response import ZendeskKBSectionResponse

class TestZendeskKBSectionResponse(unittest.TestCase):
    """ZendeskKBSectionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ZendeskKBSectionResponse:
        """Test ZendeskKBSectionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ZendeskKBSectionResponse`
        """
        model = ZendeskKBSectionResponse()
        if include_optional:
            return ZendeskKBSectionResponse(
                id = 56,
                name = '',
                description = '',
                locale = '',
                category_id = 56,
                html_url = ''
            )
        else:
            return ZendeskKBSectionResponse(
                id = 56,
                name = '',
                description = '',
                locale = '',
                html_url = '',
        )
        """

    def testZendeskKBSectionResponse(self):
        """Test ZendeskKBSectionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
