# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.api.asana_api import AsanaApi


class TestAsanaApi(unittest.TestCase):
    """AsanaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AsanaApi()

    def tearDown(self) -> None:
        pass

    def test_get_asana_project_tasks(self) -> None:
        """Test case for get_asana_project_tasks

        Get Asana Project Tasks
        """
        pass

    def test_get_asana_projects(self) -> None:
        """Test case for get_asana_projects

        Get Asana Projects
        """
        pass

    def test_get_asana_users(self) -> None:
        """Test case for get_asana_users

        Get Asana Users
        """
        pass

    def test_get_asana_workspaces(self) -> None:
        """Test case for get_asana_workspaces

        Get Asana Workspaces
        """
        pass


if __name__ == '__main__':
    unittest.main()
