# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.api.integrations_api import IntegrationsApi


class TestIntegrationsApi(unittest.TestCase):
    """IntegrationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IntegrationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_integration(self) -> None:
        """Test case for create_integration

        Create Integration
        """
        pass

    def test_delete_integration(self) -> None:
        """Test case for delete_integration

        Delete Integration
        """
        pass

    def test_get_all_integrations(self) -> None:
        """Test case for get_all_integrations

        Get All Integrations
        """
        pass

    def test_get_integration(self) -> None:
        """Test case for get_integration

        Get Integration
        """
        pass

    def test_get_slack_channels(self) -> None:
        """Test case for get_slack_channels

        Get Slack Channels
        """
        pass

    def test_get_slack_workspaces(self) -> None:
        """Test case for get_slack_workspaces

        Get Slack Workspaces
        """
        pass

    def test_integration_callback(self) -> None:
        """Test case for integration_callback

        Integration Callback
        """
        pass

    def test_search_integrations(self) -> None:
        """Test case for search_integrations

        Search Integrations
        """
        pass


if __name__ == '__main__':
    unittest.main()
