# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.ollama_list_models_request import OllamaListModelsRequest

class TestOllamaListModelsRequest(unittest.TestCase):
    """OllamaListModelsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OllamaListModelsRequest:
        """Test OllamaListModelsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OllamaListModelsRequest`
        """
        model = OllamaListModelsRequest()
        if include_optional:
            return OllamaListModelsRequest(
                api_base_url = ''
            )
        else:
            return OllamaListModelsRequest(
                api_base_url = '',
        )
        """

    def testOllamaListModelsRequest(self):
        """Test OllamaListModelsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
