# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.document_category_bulk_delete_request import DocumentCategoryBulkDeleteRequest

class TestDocumentCategoryBulkDeleteRequest(unittest.TestCase):
    """DocumentCategoryBulkDeleteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentCategoryBulkDeleteRequest:
        """Test DocumentCategoryBulkDeleteRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentCategoryBulkDeleteRequest`
        """
        model = DocumentCategoryBulkDeleteRequest()
        if include_optional:
            return DocumentCategoryBulkDeleteRequest(
                items = [
                    ''
                    ]
            )
        else:
            return DocumentCategoryBulkDeleteRequest(
                items = [
                    ''
                    ],
        )
        """

    def testDocumentCategoryBulkDeleteRequest(self):
        """Test DocumentCategoryBulkDeleteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
