# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.flow_batch_run_detail_response import FlowBatchRunDetailResponse

class TestFlowBatchRunDetailResponse(unittest.TestCase):
    """FlowBatchRunDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlowBatchRunDetailResponse:
        """Test FlowBatchRunDetailResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlowBatchRunDetailResponse`
        """
        model = FlowBatchRunDetailResponse()
        if include_optional:
            return FlowBatchRunDetailResponse(
                batch_run_id = '',
                flow_id = '',
                workspace_id = '',
                user_id = '',
                name = '',
                columns = [
                    flowhunt.models.flow_batch_column_definition.FlowBatchColumnDefinition(
                        name = '', 
                        key = '', )
                    ],
                max_parallel = 56,
                status = 'draft',
                total_rows = 56,
                completed_rows = 56,
                failed_rows = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                rows = [
                    flowhunt.models.flow_batch_row_response.FlowBatchRowResponse(
                        row_id = '', 
                        batch_run_id = '', 
                        row_index = 56, 
                        input_data = { }, 
                        status = 'pending', 
                        output = '', 
                        output_artefacts = [
                            flowhunt.models.flow_batch_artefact_info.FlowBatchArtefactInfo(
                                id = '', 
                                name = '', 
                                size = 56, 
                                mime_type = '', 
                                download_url = '', )
                            ], 
                        error = '', 
                        session_id = '', 
                        credits_used = 1.337, 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_cursor = 56
            )
        else:
            return FlowBatchRunDetailResponse(
                batch_run_id = '',
                flow_id = '',
                workspace_id = '',
                name = '',
                max_parallel = 56,
                status = 'draft',
                total_rows = 56,
                completed_rows = 56,
                failed_rows = 56,
        )
        """

    def testFlowBatchRunDetailResponse(self):
        """Test FlowBatchRunDetailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
