# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.project_issue_tag_response import ProjectIssueTagResponse

class TestProjectIssueTagResponse(unittest.TestCase):
    """ProjectIssueTagResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectIssueTagResponse:
        """Test ProjectIssueTagResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectIssueTagResponse`
        """
        model = ProjectIssueTagResponse()
        if include_optional:
            return ProjectIssueTagResponse(
                id = '',
                project_id = '',
                name = '',
                description = '',
                color = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ProjectIssueTagResponse(
                id = '',
                project_id = '',
                name = '',
                color = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testProjectIssueTagResponse(self):
        """Test ProjectIssueTagResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
