# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.project_inbox_entry_response import ProjectInboxEntryResponse

class TestProjectInboxEntryResponse(unittest.TestCase):
    """ProjectInboxEntryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectInboxEntryResponse:
        """Test ProjectInboxEntryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectInboxEntryResponse`
        """
        model = ProjectInboxEntryResponse()
        if include_optional:
            return ProjectInboxEntryResponse(
                id = '',
                workspace_id = '',
                project_id = '',
                kind = '',
                status = '',
                title = '',
                body = '',
                issue_id = '',
                session_id = '',
                metadata = { },
                created_at = '',
                updated_at = ''
            )
        else:
            return ProjectInboxEntryResponse(
                id = '',
                workspace_id = '',
                project_id = '',
                kind = '',
                status = '',
                title = '',
                body = '',
                issue_id = '',
                session_id = '',
                metadata = { },
                created_at = '',
                updated_at = '',
        )
        """

    def testProjectInboxEntryResponse(self):
        """Test ProjectInboxEntryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
