# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt-python-sdk.models.flow_request_chat_role import FlowRequestChatRole

class TestFlowRequestChatRole(unittest.TestCase):
    """FlowRequestChatRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFlowRequestChatRole(self):
        """Test FlowRequestChatRole"""
        # inst = FlowRequestChatRole()

if __name__ == '__main__':
    unittest.main()
