# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.integration_gateway_response import IntegrationGatewayResponse

class TestIntegrationGatewayResponse(unittest.TestCase):
    """IntegrationGatewayResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntegrationGatewayResponse:
        """Test IntegrationGatewayResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntegrationGatewayResponse`
        """
        model = IntegrationGatewayResponse()
        if include_optional:
            return IntegrationGatewayResponse(
                workspace_id = '',
                slug = '',
                session_id = ''
            )
        else:
            return IntegrationGatewayResponse(
                workspace_id = '',
                slug = '',
        )
        """

    def testIntegrationGatewayResponse(self):
        """Test IntegrationGatewayResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
