# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.asana_project_response import AsanaProjectResponse

class TestAsanaProjectResponse(unittest.TestCase):
    """AsanaProjectResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AsanaProjectResponse:
        """Test AsanaProjectResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AsanaProjectResponse`
        """
        model = AsanaProjectResponse()
        if include_optional:
            return AsanaProjectResponse(
                project_gid = '',
                project_name = '',
                archived = True
            )
        else:
            return AsanaProjectResponse(
                project_gid = '',
                project_name = '',
        )
        """

    def testAsanaProjectResponse(self):
        """Test AsanaProjectResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
