# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.user_plan_response import UserPlanResponse

class TestUserPlanResponse(unittest.TestCase):
    """UserPlanResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserPlanResponse:
        """Test UserPlanResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserPlanResponse`
        """
        model = UserPlanResponse()
        if include_optional:
            return UserPlanResponse(
                product_id = '',
                price_amount = 56,
                price_currency = '',
                last_renewal_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                monthly_topup_credits = 56,
                trial_end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                subscription_plan = 'S'
            )
        else:
            return UserPlanResponse(
                product_id = '',
                price_amount = 56,
                price_currency = '',
                monthly_topup_credits = 56,
                subscription_plan = 'S',
        )
        """

    def testUserPlanResponse(self):
        """Test UserPlanResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
