# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.serp_cluster_query_intersections_request import SerpClusterQueryIntersectionsRequest

class TestSerpClusterQueryIntersectionsRequest(unittest.TestCase):
    """SerpClusterQueryIntersectionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SerpClusterQueryIntersectionsRequest:
        """Test SerpClusterQueryIntersectionsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SerpClusterQueryIntersectionsRequest`
        """
        model = SerpClusterQueryIntersectionsRequest()
        if include_optional:
            return SerpClusterQueryIntersectionsRequest(
                post_back_url = '',
                query = '',
                country = '',
                language = '',
                location = '',
                group_name = '',
                group_id = '',
                live_mode = True,
                max_position = 56
            )
        else:
            return SerpClusterQueryIntersectionsRequest(
        )
        """

    def testSerpClusterQueryIntersectionsRequest(self):
        """Test SerpClusterQueryIntersectionsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
