# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt-python-sdk.models.flow_session_status import FlowSessionStatus

class TestFlowSessionStatus(unittest.TestCase):
    """FlowSessionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFlowSessionStatus(self):
        """Test FlowSessionStatus"""
        # inst = FlowSessionStatus()

if __name__ == '__main__':
    unittest.main()
