# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.flow_session_hook_waiting_metadata import FlowSessionHookWaitingMetadata

class TestFlowSessionHookWaitingMetadata(unittest.TestCase):
    """FlowSessionHookWaitingMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlowSessionHookWaitingMetadata:
        """Test FlowSessionHookWaitingMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlowSessionHookWaitingMetadata`
        """
        model = FlowSessionHookWaitingMetadata()
        if include_optional:
            return FlowSessionHookWaitingMetadata(
                hook_id = '',
                hook_name = '',
                prompt_message = ''
            )
        else:
            return FlowSessionHookWaitingMetadata(
                hook_id = '',
                hook_name = '',
                prompt_message = '',
        )
        """

    def testFlowSessionHookWaitingMetadata(self):
        """Test FlowSessionHookWaitingMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
