# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.google_drive_search_response import GoogleDriveSearchResponse

class TestGoogleDriveSearchResponse(unittest.TestCase):
    """GoogleDriveSearchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GoogleDriveSearchResponse:
        """Test GoogleDriveSearchResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GoogleDriveSearchResponse`
        """
        model = GoogleDriveSearchResponse()
        if include_optional:
            return GoogleDriveSearchResponse(
                next_page_token = '',
                files = [
                    flowhunt.models.google_drive_file_response.GoogleDriveFileResponse(
                        kind = '', 
                        mime_type = '', 
                        id = '', 
                        name = '', )
                    ]
            )
        else:
            return GoogleDriveSearchResponse(
                files = [
                    flowhunt.models.google_drive_file_response.GoogleDriveFileResponse(
                        kind = '', 
                        mime_type = '', 
                        id = '', 
                        name = '', )
                    ],
        )
        """

    def testGoogleDriveSearchResponse(self):
        """Test GoogleDriveSearchResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
