# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.agent_team_project_create import AgentTeamProjectCreate

class TestAgentTeamProjectCreate(unittest.TestCase):
    """AgentTeamProjectCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentTeamProjectCreate:
        """Test AgentTeamProjectCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentTeamProjectCreate`
        """
        model = AgentTeamProjectCreate()
        if include_optional:
            return AgentTeamProjectCreate(
                name = '',
                description = '',
                specification = '',
                color = '',
                icon = '',
                image_url = '',
                channel_spec = { },
                agents_spec = { },
                max_task_concurrency = 1.0,
                hitl_mode = 'disabled',
                hitl_approved_tools = [
                    ''
                    ],
                sandbox_enabled = True,
                sandbox_clone_url = '',
                sandbox_clone_ref = '',
                template_id = ''
            )
        else:
            return AgentTeamProjectCreate(
                name = '',
        )
        """

    def testAgentTeamProjectCreate(self):
        """Test AgentTeamProjectCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
