# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.project_issue_update import ProjectIssueUpdate

class TestProjectIssueUpdate(unittest.TestCase):
    """ProjectIssueUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectIssueUpdate:
        """Test ProjectIssueUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectIssueUpdate`
        """
        model = ProjectIssueUpdate()
        if include_optional:
            return ProjectIssueUpdate(
                title = '',
                description = '',
                status = '',
                issue_type = '',
                frequency = '',
                next_run = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tag_ids = [
                    ''
                    ]
            )
        else:
            return ProjectIssueUpdate(
        )
        """

    def testProjectIssueUpdate(self):
        """Test ProjectIssueUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
