# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.git_lab_projects_response import GitLabProjectsResponse

class TestGitLabProjectsResponse(unittest.TestCase):
    """GitLabProjectsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GitLabProjectsResponse:
        """Test GitLabProjectsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GitLabProjectsResponse`
        """
        model = GitLabProjectsResponse()
        if include_optional:
            return GitLabProjectsResponse(
                projects = [
                    flowhunt.models.git_lab_project_response.GitLabProjectResponse(
                        id = 56, 
                        name = '', 
                        path_with_namespace = '', 
                        web_url = '', 
                        visibility = '', 
                        default_branch = '', )
                    ]
            )
        else:
            return GitLabProjectsResponse(
                projects = [
                    flowhunt.models.git_lab_project_response.GitLabProjectResponse(
                        id = 56, 
                        name = '', 
                        path_with_namespace = '', 
                        web_url = '', 
                        visibility = '', 
                        default_branch = '', )
                    ],
        )
        """

    def testGitLabProjectsResponse(self):
        """Test GitLabProjectsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
