# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.workspace_auto_recharge_request import WorkspaceAutoRechargeRequest

class TestWorkspaceAutoRechargeRequest(unittest.TestCase):
    """WorkspaceAutoRechargeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceAutoRechargeRequest:
        """Test WorkspaceAutoRechargeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceAutoRechargeRequest`
        """
        model = WorkspaceAutoRechargeRequest()
        if include_optional:
            return WorkspaceAutoRechargeRequest(
                enabled = True,
                threshold = 1000000,
                amount = 10000000
            )
        else:
            return WorkspaceAutoRechargeRequest(
                enabled = True,
        )
        """

    def testWorkspaceAutoRechargeRequest(self):
        """Test WorkspaceAutoRechargeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
