# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.ai_project_template_detail_response import AIProjectTemplateDetailResponse

class TestAIProjectTemplateDetailResponse(unittest.TestCase):
    """AIProjectTemplateDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AIProjectTemplateDetailResponse:
        """Test AIProjectTemplateDetailResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AIProjectTemplateDetailResponse`
        """
        model = AIProjectTemplateDetailResponse()
        if include_optional:
            return AIProjectTemplateDetailResponse(
                id = '',
                version = 56,
                role = 'marketing',
                team_size_bucket = 'solo',
                integrations_for_card = [
                    ''
                    ],
                tags = [
                    ''
                    ],
                aha_pick = True,
                popular = True,
                setup_time_label = '',
                hire_count = 56,
                rating = 1.337,
                name = '',
                tagline = '',
                description = '',
                icon_emoji = '',
                icon_color_class = 'ic-blue',
                banner_style = 'banner-research',
                team_preview = flowhunt.models.team_preview.TeamPreview(
                    agent_count = 1.0, 
                    supervisor_label = 'Supervisor', 
                    avatars = [
                        flowhunt.models.avatar_chip.AvatarChip(
                            initial = '0', 
                            bg = '#62ECB0', 
                            fg = '#62ECB0', 
                            role = '', )
                        ], ),
                required_integrations = [
                    flowhunt.models.required_integration.RequiredIntegration(
                        slug = '0', 
                        purpose = '', )
                    ],
                initial_periodic_issue = flowhunt.models.initial_issue_seed.InitialIssueSeed(
                    title = '0', 
                    description = '', 
                    type = 'normal', 
                    frequency = '', 
                    tag_refs = [
                        ''
                        ], )
            )
        else:
            return AIProjectTemplateDetailResponse(
                id = '',
                version = 56,
                role = 'marketing',
                team_size_bucket = 'solo',
                integrations_for_card = [
                    ''
                    ],
                tags = [
                    ''
                    ],
                aha_pick = True,
                popular = True,
                setup_time_label = '',
                hire_count = 56,
                rating = 1.337,
                name = '',
                tagline = '',
                description = '',
                icon_emoji = '',
                icon_color_class = 'ic-blue',
                banner_style = 'banner-research',
                team_preview = flowhunt.models.team_preview.TeamPreview(
                    agent_count = 1.0, 
                    supervisor_label = 'Supervisor', 
                    avatars = [
                        flowhunt.models.avatar_chip.AvatarChip(
                            initial = '0', 
                            bg = '#62ECB0', 
                            fg = '#62ECB0', 
                            role = '', )
                        ], ),
                required_integrations = [
                    flowhunt.models.required_integration.RequiredIntegration(
                        slug = '0', 
                        purpose = '', )
                    ],
                initial_periodic_issue = flowhunt.models.initial_issue_seed.InitialIssueSeed(
                    title = '0', 
                    description = '', 
                    type = 'normal', 
                    frequency = '', 
                    tag_refs = [
                        ''
                        ], ),
        )
        """

    def testAIProjectTemplateDetailResponse(self):
        """Test AIProjectTemplateDetailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
