# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.api.custom_models_api import CustomModelsApi


class TestCustomModelsApi(unittest.TestCase):
    """CustomModelsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomModelsApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_delete_custom_models(self) -> None:
        """Test case for bulk_delete_custom_models

        Bulk Delete Custom Models
        """
        pass

    def test_create_custom_model(self) -> None:
        """Test case for create_custom_model

        Create Custom Model
        """
        pass

    def test_delete_custom_model(self) -> None:
        """Test case for delete_custom_model

        Delete Custom Model
        """
        pass

    def test_get_available_models(self) -> None:
        """Test case for get_available_models

        Get Available Models
        """
        pass

    def test_list_ollama_models(self) -> None:
        """Test case for list_ollama_models

        List Ollama Models
        """
        pass

    def test_search_custom_models(self) -> None:
        """Test case for search_custom_models

        Search Custom Models
        """
        pass

    def test_update_custom_model(self) -> None:
        """Test case for update_custom_model

        Update Custom Model
        """
        pass


if __name__ == '__main__':
    unittest.main()
