# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.image_ft_train_request import ImageFTTrainRequest

class TestImageFTTrainRequest(unittest.TestCase):
    """ImageFTTrainRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageFTTrainRequest:
        """Test ImageFTTrainRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageFTTrainRequest`
        """
        model = ImageFTTrainRequest()
        if include_optional:
            return ImageFTTrainRequest(
                trigger_word = 'Trigger word 1'
            )
        else:
            return ImageFTTrainRequest(
                trigger_word = 'Trigger word 1',
        )
        """

    def testImageFTTrainRequest(self):
        """Test ImageFTTrainRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
