# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt.models.google_ads_conversion_tracking_status_enum import GoogleAdsConversionTrackingStatusEnum

class TestGoogleAdsConversionTrackingStatusEnum(unittest.TestCase):
    """GoogleAdsConversionTrackingStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGoogleAdsConversionTrackingStatusEnum(self):
        """Test GoogleAdsConversionTrackingStatusEnum"""
        # inst = GoogleAdsConversionTrackingStatusEnum()

if __name__ == '__main__':
    unittest.main()
