# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flowhunt-python-sdk.models.api_integration_create_request import ApiIntegrationCreateRequest

class TestApiIntegrationCreateRequest(unittest.TestCase):
    """ApiIntegrationCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiIntegrationCreateRequest:
        """Test ApiIntegrationCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiIntegrationCreateRequest`
        """
        model = ApiIntegrationCreateRequest()
        if include_optional:
            return ApiIntegrationCreateRequest(
                servers = [https://api.com],
                name = 'API Integration',
                description = 'API Integration'
            )
        else:
            return ApiIntegrationCreateRequest(
                servers = [https://api.com],
                name = 'API Integration',
                description = 'API Integration',
        )
        """

    def testApiIntegrationCreateRequest(self):
        """Test ApiIntegrationCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
