# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class AIStudioFlowTemplateResponse(BaseModel):
    """
    AIStudioFlowTemplateResponse
    """ # noqa: E501
    id: StrictStr
    version: StrictInt
    flow_id: StrictStr
    engine_version: StrictStr
    category: StrictStr
    tags: List[StrictStr]
    aha_pick: StrictBool
    popular: StrictBool
    hire_count: StrictInt
    rating: Union[StrictFloat, StrictInt]
    estimated_run_time_label: StrictStr
    name: StrictStr
    tagline: StrictStr
    description: StrictStr
    icon_emoji: StrictStr
    icon_color_class: StrictStr
    banner_style: StrictStr
    inputs_summary: StrictStr
    outputs_summary: StrictStr
    integrations_for_card: List[StrictStr]
    __properties: ClassVar[List[str]] = ["id", "version", "flow_id", "engine_version", "category", "tags", "aha_pick", "popular", "hire_count", "rating", "estimated_run_time_label", "name", "tagline", "description", "icon_emoji", "icon_color_class", "banner_style", "inputs_summary", "outputs_summary", "integrations_for_card"]

    @field_validator('engine_version')
    def engine_version_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['v2', 'v3']):
            raise ValueError("must be one of enum values ('v2', 'v3')")
        return value

    @field_validator('category')
    def category_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['research', 'marketing', 'sales', 'support', 'content', 'ops', 'engineering', 'data']):
            raise ValueError("must be one of enum values ('research', 'marketing', 'sales', 'support', 'content', 'ops', 'engineering', 'data')")
        return value

    @field_validator('icon_color_class')
    def icon_color_class_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ic-blue', 'ic-pink', 'ic-amber', 'ic-green', 'ic-violet', 'ic-cyan', 'ic-rose', 'ic-slate', 'ic-orange', 'ic-teal', 'ic-indigo', 'ic-yellow']):
            raise ValueError("must be one of enum values ('ic-blue', 'ic-pink', 'ic-amber', 'ic-green', 'ic-violet', 'ic-cyan', 'ic-rose', 'ic-slate', 'ic-orange', 'ic-teal', 'ic-indigo', 'ic-yellow')")
        return value

    @field_validator('banner_style')
    def banner_style_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['banner-research', 'banner-content', 'banner-sales']):
            raise ValueError("must be one of enum values ('banner-research', 'banner-content', 'banner-sales')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AIStudioFlowTemplateResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AIStudioFlowTemplateResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "version": obj.get("version"),
            "flow_id": obj.get("flow_id"),
            "engine_version": obj.get("engine_version"),
            "category": obj.get("category"),
            "tags": obj.get("tags"),
            "aha_pick": obj.get("aha_pick"),
            "popular": obj.get("popular"),
            "hire_count": obj.get("hire_count"),
            "rating": obj.get("rating"),
            "estimated_run_time_label": obj.get("estimated_run_time_label"),
            "name": obj.get("name"),
            "tagline": obj.get("tagline"),
            "description": obj.get("description"),
            "icon_emoji": obj.get("icon_emoji"),
            "icon_color_class": obj.get("icon_color_class"),
            "banner_style": obj.get("banner_style"),
            "inputs_summary": obj.get("inputs_summary"),
            "outputs_summary": obj.get("outputs_summary"),
            "integrations_for_card": obj.get("integrations_for_card")
        })
        return _obj


