# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BrandingUpdateRequest(BaseModel):
    """
    BrandingUpdateRequest
    """ # noqa: E501
    branding_logo_url: Optional[StrictStr] = None
    brand_avatar_url: Optional[StrictStr] = None
    slug: Optional[StrictStr] = None
    dashboard_primary_color: Optional[StrictStr] = None
    dashboard_secondary_color: Optional[StrictStr] = None
    show_ads_ai: Optional[StrictBool] = None
    show_photomatic_ai: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["branding_logo_url", "brand_avatar_url", "slug", "dashboard_primary_color", "dashboard_secondary_color", "show_ads_ai", "show_photomatic_ai"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BrandingUpdateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BrandingUpdateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "branding_logo_url": obj.get("branding_logo_url"),
            "brand_avatar_url": obj.get("brand_avatar_url"),
            "slug": obj.get("slug"),
            "dashboard_primary_color": obj.get("dashboard_primary_color"),
            "dashboard_secondary_color": obj.get("dashboard_secondary_color"),
            "show_ads_ai": obj.get("show_ads_ai"),
            "show_photomatic_ai": obj.get("show_photomatic_ai")
        })
        return _obj


