# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from flowhunt.models.match_filter import MatchFilter
from flowhunt.models.range_filter import RangeFilter
from flowhunt.models.term_filter import TermFilter
from flowhunt.models.terms_filter import TermsFilter
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

FILTERSVALUE_ONE_OF_SCHEMAS = ["MatchFilter", "RangeFilter", "TermFilter", "TermsFilter"]

class FiltersValue(BaseModel):
    """
    FiltersValue
    """
    # data type: TermFilter
    oneof_schema_1_validator: Optional[TermFilter] = None
    # data type: TermsFilter
    oneof_schema_2_validator: Optional[TermsFilter] = None
    # data type: MatchFilter
    oneof_schema_3_validator: Optional[MatchFilter] = None
    # data type: RangeFilter
    oneof_schema_4_validator: Optional[RangeFilter] = None
    actual_instance: Optional[Union[MatchFilter, RangeFilter, TermFilter, TermsFilter]] = None
    one_of_schemas: Set[str] = { "MatchFilter", "RangeFilter", "TermFilter", "TermsFilter" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = FiltersValue.model_construct()
        error_messages = []
        match = 0
        # validate data type: TermFilter
        if not isinstance(v, TermFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TermFilter`")
        else:
            match += 1
        # validate data type: TermsFilter
        if not isinstance(v, TermsFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TermsFilter`")
        else:
            match += 1
        # validate data type: MatchFilter
        if not isinstance(v, MatchFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MatchFilter`")
        else:
            match += 1
        # validate data type: RangeFilter
        if not isinstance(v, RangeFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RangeFilter`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in FiltersValue with oneOf schemas: MatchFilter, RangeFilter, TermFilter, TermsFilter. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in FiltersValue with oneOf schemas: MatchFilter, RangeFilter, TermFilter, TermsFilter. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into TermFilter
        try:
            instance.actual_instance = TermFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TermsFilter
        try:
            instance.actual_instance = TermsFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MatchFilter
        try:
            instance.actual_instance = MatchFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RangeFilter
        try:
            instance.actual_instance = RangeFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into FiltersValue with oneOf schemas: MatchFilter, RangeFilter, TermFilter, TermsFilter. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into FiltersValue with oneOf schemas: MatchFilter, RangeFilter, TermFilter, TermsFilter. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], MatchFilter, RangeFilter, TermFilter, TermsFilter]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


