# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class GenerateAgentConfigRequest(BaseModel):
    """
    GenerateAgentConfigRequest
    """ # noqa: E501
    agent_type: Optional[Annotated[str, Field(strict=True)]] = Field(default='worker', description="The type of agent: supervisor, lead, or worker. Optional for edit_team mode.")
    description: Optional[Annotated[str, Field(strict=True, max_length=2000)]] = Field(default=None, description="What is this agent used for? Required for single_agent/full_team/project_only modes.")
    agents_spec: Optional[Dict[str, Any]] = Field(default=None, description="Current team agents_spec for context")
    mode: Optional[Annotated[str, Field(strict=True)]] = Field(default='single_agent', description="Generation mode: single_agent, full_team, project_only, or edit_team")
    message: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, description="User message for edit_team mode (what to change)")
    __properties: ClassVar[List[str]] = ["agent_type", "description", "agents_spec", "mode", "message"]

    @field_validator('agent_type')
    def agent_type_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(supervisor|lead|worker)$", value):
            raise ValueError(r"must validate the regular expression /^(supervisor|lead|worker)$/")
        return value

    @field_validator('mode')
    def mode_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(single_agent|full_team|project_only|edit_team)$", value):
            raise ValueError(r"must validate the regular expression /^(single_agent|full_team|project_only|edit_team)$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenerateAgentConfigRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenerateAgentConfigRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_type": obj.get("agent_type") if obj.get("agent_type") is not None else 'worker',
            "description": obj.get("description"),
            "agents_spec": obj.get("agents_spec"),
            "mode": obj.get("mode") if obj.get("mode") is not None else 'single_agent',
            "message": obj.get("message")
        })
        return _obj


