# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from flowhunt.models.aspec_ratio import AspecRatio
from flowhunt.models.base_foundation_model import BaseFoundationModel
from flowhunt.models.inference_history_search_request_search_after_inner import InferenceHistorySearchRequestSearchAfterInner
from typing import Optional, Set
from typing_extensions import Self

class InferenceHistorySearchRequest(BaseModel):
    """
    InferenceHistorySearchRequest
    """ # noqa: E501
    from_date: Optional[datetime] = Field(default=None, description="From date")
    to_date: Optional[datetime] = Field(default=None, description="To date")
    limit: Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]] = Field(default=10, description="The number of results to return")
    search_after: Optional[List[InferenceHistorySearchRequestSearchAfterInner]] = Field(default=None, description="The search_after parameter for pagination (contains sort values from previous page)")
    base_model: Optional[BaseFoundationModel] = Field(default=None, description="The base model to filter by")
    style: Optional[StrictStr] = Field(default=None, description="The style to filter by")
    effect: Optional[StrictStr] = Field(default=None, description="The effect to filter by")
    aspect_ratio: Optional[AspecRatio] = Field(default=None, description="The aspect ratio to filter by")
    __properties: ClassVar[List[str]] = ["from_date", "to_date", "limit", "search_after", "base_model", "style", "effect", "aspect_ratio"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InferenceHistorySearchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in search_after (list)
        _items = []
        if self.search_after:
            for _item_search_after in self.search_after:
                if _item_search_after:
                    _items.append(_item_search_after.to_dict())
            _dict['search_after'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InferenceHistorySearchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "from_date": obj.get("from_date"),
            "to_date": obj.get("to_date"),
            "limit": obj.get("limit") if obj.get("limit") is not None else 10,
            "search_after": [InferenceHistorySearchRequestSearchAfterInner.from_dict(_item) for _item in obj["search_after"]] if obj.get("search_after") is not None else None,
            "base_model": obj.get("base_model"),
            "style": obj.get("style"),
            "effect": obj.get("effect"),
            "aspect_ratio": obj.get("aspect_ratio")
        })
        return _obj


