# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MCPConnectorResponse(BaseModel):
    """
    Response shape — never includes plaintext auth secrets. Only the auth_type is exposed; the presence of a secret is signalled via ``has_credentials``.
    """ # noqa: E501
    workspace_id: StrictStr
    connector_id: StrictStr
    name: StrictStr
    url: StrictStr
    transport: StrictStr
    auth_type: StrictStr
    has_credentials: StrictBool = Field(description="True if encrypted credentials are stored on this connector")
    headers: Optional[Dict[str, StrictStr]] = Field(default=None, description="Non-secret custom headers")
    created_at: datetime
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["workspace_id", "connector_id", "name", "url", "transport", "auth_type", "has_credentials", "headers", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MCPConnectorResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MCPConnectorResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workspace_id": obj.get("workspace_id"),
            "connector_id": obj.get("connector_id"),
            "name": obj.get("name"),
            "url": obj.get("url"),
            "transport": obj.get("transport"),
            "auth_type": obj.get("auth_type"),
            "has_credentials": obj.get("has_credentials"),
            "headers": obj.get("headers"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


