# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ProjectIssueCommentArtefactResponse(BaseModel):
    """
    ProjectIssueCommentArtefactResponse
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default='', description="Artefact ID")
    name: Optional[StrictStr] = Field(default='', description="File name")
    relative_path: Optional[StrictStr] = Field(default='', description="Relative path in workspace")
    s3_key: Optional[StrictStr] = Field(default='', description="S3 object key")
    mime_type: Optional[StrictStr] = Field(default='', description="MIME type")
    size: Optional[StrictInt] = Field(default=0, description="File size in bytes")
    modified_at: Optional[StrictStr] = Field(default='', description="Last modified timestamp")
    download_url: Optional[StrictStr] = Field(default='', description="Direct download URL")
    __properties: ClassVar[List[str]] = ["id", "name", "relative_path", "s3_key", "mime_type", "size", "modified_at", "download_url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProjectIssueCommentArtefactResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProjectIssueCommentArtefactResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id") if obj.get("id") is not None else '',
            "name": obj.get("name") if obj.get("name") is not None else '',
            "relative_path": obj.get("relative_path") if obj.get("relative_path") is not None else '',
            "s3_key": obj.get("s3_key") if obj.get("s3_key") is not None else '',
            "mime_type": obj.get("mime_type") if obj.get("mime_type") is not None else '',
            "size": obj.get("size") if obj.get("size") is not None else 0,
            "modified_at": obj.get("modified_at") if obj.get("modified_at") is not None else '',
            "download_url": obj.get("download_url") if obj.get("download_url") is not None else ''
        })
        return _obj


