# coding: utf-8

"""
    FlowHunt

    FlowHunt API

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ProjectIssueCreate(BaseModel):
    """
    ProjectIssueCreate
    """ # noqa: E501
    title: StrictStr = Field(description="Issue title")
    description: Optional[StrictStr] = Field(default=None, description="Issue description")
    status: Optional[StrictStr] = Field(default=None, description="Issue status")
    issue_type: Optional[StrictStr] = Field(default='normal', description="Issue type: normal or periodic")
    frequency: Optional[StrictStr] = Field(default=None, description="Frequency for periodic issues (e.g. daily, weekly)")
    next_run: Optional[datetime] = Field(default=None, description="Schedule this issue to run at a specific UTC time. Leave empty to run on the next dispatcher tick.")
    tag_ids: Optional[List[StrictStr]] = Field(default=None, description="Tag IDs")
    __properties: ClassVar[List[str]] = ["title", "description", "status", "issue_type", "frequency", "next_run", "tag_ids"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProjectIssueCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProjectIssueCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "description": obj.get("description"),
            "status": obj.get("status"),
            "issue_type": obj.get("issue_type") if obj.get("issue_type") is not None else 'normal',
            "frequency": obj.get("frequency"),
            "next_run": obj.get("next_run"),
            "tag_ids": obj.get("tag_ids")
        })
        return _obj


